fix(badge): change rings for borders
adevinta/spark pull request #1534
Opened 2023-10-05 13:33 UTC by andresin87

**TASK**: 

### Description, Motivation and Context

### Types of changes

- [x] 🪲 Bug fix (non-breaking change which fixes an issue)

### Screenshots - Animations

2023-10-05 13:34 UTC, soykje approved these changes

2023-10-05 13:42 UTC, andresin87 commented
It also has the fix @Powerplex said

2023-10-05 13:44 UTC, acd02 approved these changes

2023-10-05 16:43 UTC, Powerplex requested changes
It introduces un unwanted change on the size of the "no count" version:
https://github.com/adevinta/spark/assets/2033710/be9f183b-af29-41f6-9f1e-0cb246c5119e

2023-10-06 08:06 UTC, Powerplex approved these changes

2023-10-06 08:11 UTC, merged